services:
  backend:
    build:
      dockerfile: api/Dockerfile
      # context: .
    environment:
      - XI_API_KEY=${XI_API_KEY}

  frontend:
    build:
      dockerfile: web/Dockerfile
      # context: .
    ports:
      - 8080:80

networks:
  default: {}
